# API server - points to load balancer
address=/api.okd.kubesoar.com/192.168.1.20

# Internal API - points to load balancer
address=/api-int.okd.kubesoar.com/192.168.1.20

# Apps wildcard - for ingress via load balancer
address=/.apps.okd.kubesoar.com/192.168.1.20

# BYOC Logs external services on desktop-server / laptop-server
address=/pihole.kubesoar.com/192.168.1.5
address=/postgres.kubesoar.com/192.168.1.25
address=/minio.kubesoar.com/192.168.1.26

# Master nodes
address=/master-0.okd.kubesoar.com/192.168.1.22
address=/master-1.okd.kubesoar.com/192.168.1.23
address=/master-2.okd.kubesoar.com/192.168.1.24

# ETCD SRV records
srv-host=_etcd-server-ssl._tcp.okd.kubesoar.com,master-0.okd.kubesoar.com,2380,0,10
srv-host=_etcd-server-ssl._tcp.okd.kubesoar.com,master-1.okd.kubesoar.com,2380,0,10
srv-host=_etcd-server-ssl._tcp.okd.kubesoar.com,master-2.okd.kubesoar.com,2380,0,10

# PTR records
ptr-record=10.1.168.192.in-addr.arpa,master-0.okd.kubesoar.com
ptr-record=11.1.168.192.in-addr.arpa,master-1.okd.kubesoar.com
ptr-record=12.1.168.192.in-addr.arpa,master-2.okd.kubesoar.com
