apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: azure
      mappingMethod: claim
      type: OpenID
      openID:
        clientID: "b823028f-f865-4b38-8991-c482050dbc9b"
        clientSecret:
          name: "azure-oauth-client-secret"
        issuer: "https://login.microsoftonline.com/cbba7299-bd72-49e3-9abf-7d88aaf531c3/v2.0"
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - email
        extraAuthorizeParameters:
          include_granted_scopes: "true"
        extraScopes:
          - profile
          - email
          - openid
