apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: freeipa
spec:
  identityProviders:
    - ldap:
        attributes:
          email:
            - mail
          id:
            - uid
          name:
            - cn
          preferredUsername:
            - uid
        bindDN: 'uid=admin,cn=users,cn=accounts,dc=kubesoar,dc=com'
        bindPassword:
          name: ldap-bind-password-62f64
        ca:
          name: ldap-ca-mk4th
        insecure: false
        url: 'ldap://idm.kubesoar.com:389'
      mappingMethod: claim
      name: ldap
      type: LDAP